name: Test and build PR

on: [pull_request, workflow_dispatch]

env:
  TERMINUS_FETCH_API_KEY: 'placeholder'

jobs:
  build:
    name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x', '20.x']
        os: [windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci --omit=optional

      - name: Test
        run: npm test --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
